version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
              python3 -m venv env
              . env/bin/activate
              pip install -r requirements.txt
      - run:
          name: Validate playbook syntax
          command: |
              . env/bin/activate
              ansible-playbook main_ec2.yml --syntax-check
              ansible-playbook main_ec2_idempotent.yml --syntax-check

workflows:
  version: 2
  build:
    jobs:
      - build
