version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
              python3 -m venv env
              . env/bin/activate
              pip install -r requirements.txt

workflows:
  version: 2
  build:
    jobs:
      - build
